name: Generar grafico Bomberman

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Generar grafico de contribuciones
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: maysalazar16
          games: 'bomberman'
      - name: Publicar en la rama pacman-output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: pacman-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
